
# This file contains Tcl code used by the scripts that generate web-pages 
# (mkwebpage.tcl, mksupportpage.tcl) to generate the boxes on the left-hand
# side of the pages.
#

# This global variable contains the complete html text of the 
# "Site Contents" box.
set ::SiteMap {
    <!--
  	The following <div> block implements the "Site Contents" box. The
  	original text (from which each page copies this block) is contained in
  	the file webpage/common.tcl of the source distribution. If you need to
  	edit it, change it in webpage/common.tcl and regenerate the site.
    -->
    <div id="sitemap">
      <h3>Site Contents</h3><ul>
      <ul>
        <li> <a href="index.html">Home</a>
             <span class="caption">Front page of this site</span>
        <li> <a href="support.html">Standards</a>
             <span class="caption">
                 Summary of support for CSS and HTML standards</span>
        <li> <a href="tkhtml.html">Man page</a>
             <span class="caption">
                 Unix style manual page for the widget.
             </span>
        <li> <a href="hv3.html">Hv3</a>
             <span class="caption">
		 Page for the demo/test application hv3. Screenshots and
                 starpacks for windows and linux are available here.
             </span>
        <li> <a href="requirements.html">Requirements</a>
             <span class="caption">
                 Requirements document for Tkhtml 3.
             </span>
        <li> <a href="http://tkhtml.tcl.tk/cvstrac/timeline">Cvstrac</a>
             <span class="caption">
		  Cvstrac is used for project change-log, wiki and bug
                  tracking.
             </span>
      </ul>
    </div>
}

set ::PageSectionList [list]
proc addPageSection {title name} {
  lappend ::PageSectionList [list $title $name]
}

proc getSideBoxes {} {
  set ret {  <div class="sidebox">}
  append ret {
    <!--
    	The following <div> block implements the "Page Contents" box.
  	This is auto-generated by code in the file webpage/common.tcl.
    -->
    <div id="toc">
      <h3>Page Contents</h3><ul>
      <ul>
  }
  foreach entry $::PageSectionList {
    foreach {caption href} $entry {}
    append ret "        <li><a href=\"#$href\">$caption</a></li>\n"
  }
  append ret "      </ul>\n    </div>"
  append ret $::SiteMap
  append ret "  </div> <!-- end of sidebox -->\n"

  return $ret
}
