
# This file contains Tcl code used by the scripts that generate web-pages 
# (mkwebpage.tcl, mksupportpage.tcl) to generate the boxes on the left-hand
# side of the pages.
#

# This global variable contains the complete html text of the 
# "Site Contents" box.
set ::SiteMap {
    <!--
  	The following <div> block implements the "Site Contents" box. The
  	original text (from which each page copies this block) is contained in
  	the file webpage/common.tcl of the source distribution. If you need to
  	edit it, change it in webpage/common.tcl and regenerate the site.
    -->
    <div id="sitemap">
      <h3>Site Contents</h3><ul>
      <ul>
        <li> <a href="index.html">Front page</a>
        <li> <a href="support.html">Supported CSS/HTML</a>
        <li> <a href="tkhtml.html">Widget man page</a>
        <li> <a href="hv3.html">hv3 (demo &amp; screenshots)</a>
        <li> <a href="requirements.html">Requirements Document</a>
        <li> <a href="http://tkhtml.tcl.tk/cvstrac/timeline">Change log (Cvstrac)</a>
      </ul>
    </div>
}

set ::PageSectionList [list]
proc addPageSection {title name} {
  lappend ::PageSectionList [list $title $name]
}

proc getSideBoxes {} {
  set ret {  <div class="sidebox">}
  append ret {
    <!--
    	The following <div> block implements the "Page Contents" box.
  	This is auto-generated by code in the file webpage/common.tcl.
    -->
    <div id="toc">
      <h3>Page Contents</h3><ul>
      <ul>
  }
  foreach entry $::PageSectionList {
    foreach {caption href} $entry {}
    append ret "        <li><a href=\"#$href\">$caption</a></li>\n"
  }
  append ret "      </ul>\n    </div>"
  append ret $::SiteMap
  append ret "  </div> <!-- end of sidebox -->\n"

  return $ret
}
