char HtmlLib[] = 
"set @Html_VersionNumber 0\n"
"set @Html_ReleaseNumber 1\n"
"set @Html_BuildNumber 46 \n"
"proc @Html_Textarea_Build {w c r wrap} {\n"
"frame $w.f -bd 0\n"
"pack $w.f -side top -fill both -expand 1\n"
"text $w.f.t -width $c -height $r -wrap $wrap -xscrollcommand \"$w.hsb set\" \\\n"
"-yscrollcommand \"$w.f.vsb set\"\n"
"pack $w.f.t -side left -fill both -expand 1\n"
"scrollbar $w.f.vsb -orient vertical -command \"$w.f.t yview\" -width 9\n"
"pack $w.f.vsb -side left -fill y\n"
"frame $w.sp -width [winfo reqwidth $w.f.vsb]\n"
"pack $w.sp -side right\n"
"scrollbar $w.hsb -orient horizontal -command \"$w.f.t xview\" -width 9\n"
"pack $w.hsb -side top -fill x\n"
"update\n"
"}\n"
"proc @Html_Textarea_Get {w} {\n"
"return [$w.f.t get 1.0 end]\n"
"}\n"
"proc @Html_Textarea_Put {w t} {\n"
"$w.f.t delete 1.0 end\n"
"$w.f.t insert end $t\n"
"}\n"
"bind HtmlClip <ButtonPress-1> {\n"
"set w [winfo parent %W]\n"
"set @Html($w:start) [$w index @%x,%y]\n"
"set @Html($w:x) %x\n"
"set @Html($w:y) %y\n"
"set @Html($w:moved) 0\n"
"}\n"
"bind HtmlClip <B1-Motion> {\n"
"set w [winfo parent %W]\n"
"if {[set @Html($w:moved)] ||\n"
"abs(%x-[set @Html($w:x)])>2 || abs(%y-[set @Html($w:y)])>2} {\n"
"set @Html($w:x) %x\n"
"set @Html($w:y) %y\n"
"set @Html($w:moved) 1\n"
"if {![info exists @Html($w:motor)]} {\n"
"@Html_Motor $w\n"
"}\n"
"}\n"
"}\n"
"bind HtmlClip <ButtonRelease-1> {\n"
"set w [winfo parent %W]\n"
"catch {after cancel [set @Html($w:motor)]}\n"
"catch {unset @Html($w:motor)}\n"
"if {![set @Html($w:moved)]} {\n"
"set url [$w href %x %y]\n"
"set cmd [$w cget -hyperlinkcommand]\n"
"if {[string length $url] && [string length $cmd]} {\n"
"eval \"$cmd 1 $url\"\n"
"}\n"
"}\n"
"}\n"
"proc @Html_Motor w {\n"
"global @Html\n"
"set x [set @Html($w:x)]\n"
"set y [set @Html($w:y)]\n"
"$w selection set [set @Html($w:start)] @$x,$y\n"
"set start 0\n"
"if {$y<0} {\n"
"after idle \"$w yview scroll -1 units\"\n"
"set start 1\n"
"} elseif {$y>[winfo height $w.x]} {\n"
"after idle \"$w yview scroll +1 units\"\n"
"set start 1\n"
"}\n"
"if {$x<0} {\n"
"after idle \"$w xview scroll -1 units\"\n"
"set start 1\n"
"} elseif {$x>[winfo width $w.x]} {\n"
"after idle \"$w xview scroll +1 units\"\n"
"set start 1\n"
"}\n"
"if {$start} {\n"
"set @Html($w:motor) [after 10 \"@Html_Motor $w\"]\n"
"} else {\n"
"catch {unset @Html($w:motor)}\n"
"}\n"
"}\n"
"bind HtmlClip <Motion> {\n"
"@Html_Hyperlink [winfo parent %W] %x %y\n"
"}\n"
"bind HtmlClip <Leave> {\n"
"@Html_Hyperlink [winfo parent %W] -100 -100\n"
"}\n"
"proc @Html_Hyperlink {w x y} {\n"
"set cmd [$w cget -hyperlinkcommand]\n"
"if {[string length $cmd]==0} return;\n"
"global @Html\n"
"set url [$w href $x $y]\n"
"if {[info exists @Html($w:url)]} {\n"
"set old [set @Html($w:url)]\n"
"} else {\n"
"set old x$url\n"
"}\n"
"if {[string compare $old $url]} {\n"
"set @Html($w:url) $url\n"
"eval \"$cmd 0 [list $url]\"\n"
"}\n"
"}\n"
;
